/*
 * THE ORDER IS BUILT IN TWO LANGUAGES, AND NOTHING CHECKED THEY STILL AGREE.
 *
 * qp decides the exit — how many parts the position is cut into, where each
 * part's target is, what the stop does — and hands it over as `exit_plan`.
 * `planOrder` reads that object and turns it into the bodies that go on the
 * wire. The field names are matched by hand, across a language boundary, and
 * EVERY WAY THEY CAN DRIFT APART IS SILENT: the JSON stays valid, SignalStack
 * accepts it, the broker acts on it, and the position is simply not the one
 * that was tested.
 *
 * Measured, not imagined. "Half at 2R, half rides the stop", 100 shares:
 *
 *     correct                     50 @ 2R  +  50 riding the stop
 *     `runner` becomes a dict     100 @ 2R         — the runner is DELETED
 *     leg `price` renamed         100, no target   — the WHOLE thing rides
 *
 * One field, either direction, and the strategy that trades is not the
 * strategy that was backtested. Neither raises. Neither logs.
 *
 * tests/fixtures/exit-plans.json is the real exit plan of every strategy the
 * platform holds, generated by chart/exports/exit_contract.py at a fixed entry
 * and stop (50.00 / 49.00, so 1R = 1.00 and 2R = 52.00). This file asserts
 * that each one still becomes the orders that strategy asks for.
 *
 * IT TESTS THE FIXTURE, NOT A HAND-WRITTEN PLAN. broker.scaleout.shapes covers
 * the splitting logic beautifully and would pass unchanged through every drift
 * above, because its plans are typed here rather than produced by qp. That is
 * the gap this closes: the shapes test says "given this plan, these orders",
 * and this one says "this plan is the one qp actually sends".
 */

const os = require('os');
const path = require('path');
const fs = require('fs');

const DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'exit-contract-'));
process.env.BROKER_FILE = path.join(DIR, 'broker.json');
process.env.BROKER_LEDGER = path.join(DIR, 'orders.jsonl');

const broker = require('../src/broker/signalstack');

// A made-up hook id. The real one is a credential — anyone holding it can
// trade the account — so it lives only in data/broker.json, which is gitignored.
const HOOK = 'https://app.signalstack.com/hook/FAKEhook0000000000000a';
const DAY = '2026-08-17';

const CONTRACT = JSON.parse(fs.readFileSync(
  path.join(__dirname, 'fixtures', 'exit-plans.json'), 'utf8'));

let cfg;
beforeEach(() => {
  fs.rmSync(process.env.BROKER_FILE, { force: true });
  fs.rmSync(process.env.BROKER_LEDGER, { force: true });
  broker.save({
    destinations: [{ id: 'ttp', name: 'TTP', dialect: 'ttp', webhookUrl: HOOK,
                     buyingPower: 1000000, ratio: 1, mode: 'auto', setups: [] }],
    enabled: true,
  });
  broker.save({ armed: true, allowShort: true });
  cfg = broker.destinationCfg('ttp');
});
afterAll(() => { fs.rmSync(DIR, { recursive: true, force: true }); });

/** The bodies that would go on the wire for one plan. */
function wire(plan, { side = 'long', quantity = 100 } = {}) {
  const long = side === 'long';
  const p = broker.planOrder({
    symbol: 'DINO',
    signal: long ? 'LONG' : 'SHORT',
    quantity,
    price: CONTRACT.entry,
    // The stop the contract was priced from — mirrored for a short, exactly as
    // the exporter does, so 1R is 1.00 on both sides.
    stop: long ? CONTRACT.stop : CONTRACT.entry + (CONTRACT.entry - CONTRACT.stop),
    // Deliberately a DIFFERENT number from any leg's target. If planOrder ever
    // falls back to this argument instead of reading the plan, the wrong price
    // is on the wire and this value is what makes that visible.
    target: 99.99,
    date: DAY, plan, cfg,
  });
  if (p.blocked) return { blocked: p.blocked, reason: p.reason };
  return { bodies: p.orders && p.orders.length ? p.orders : [p.body] };
}

const NAMED = CONTRACT.strategies.map(s => [`${s.id} ${s.name}`, s]);

describe('the fixture is the real thing', () => {
  test('it covers every strategy the platform holds', () => {
    expect(CONTRACT.strategies.length).toBeGreaterThanOrEqual(13);
  });

  /*
   * 1R = 1.00 on purpose. A fixture generated from live prices would change
   * every morning and its diff would say nothing about whether the CONTRACT
   * changed — which is the only thing it exists to show.
   */
  test('the prices are the readable ones, so a target can be checked by eye', () => {
    expect(CONTRACT.entry - CONTRACT.stop).toBe(1);
    expect(CONTRACT.target_r).toBe(2);
  });

  test('and it was generated, not typed', () => {
    expect(CONTRACT.note).toMatch(/exit_contract\.py/);
  });

  /*
   * THE FIELD NAMES, ASSERTED BY NAME.
   *
   * Without this the tests below go quietly VACUOUS on the very drift they
   * exist to catch. They read `l.price` to work out what to expect and then
   * check the wire against it — so if qp renamed `price`, both sides of every
   * assertion move together: no priced legs expected, no targets found, green.
   * The test would agree, in detail, that a position with no target is
   * correct.
   *
   * Naming the keys is the one check that cannot move with the rename. It is
   * also asserted from the qp side (logic_audit48), against the desk's own
   * source — between them, a rename in either language fails a gate.
   */
  test('the plan carries the exact keys the order builder reads', () => {
    for (const s of CONTRACT.strategies) {
      for (const [side, plan] of Object.entries(s.sides)) {
        const where = `${s.name} ${side}`;
        expect(`${where}:${Array.isArray(plan.legs)}`).toBe(`${where}:true`);
        // A number. As an object it is truthy in JS but Number({}) is NaN, so
        // the runner is silently folded into the last target.
        expect(typeof plan.runner).toBe('number');
        for (const leg of plan.legs) {
          // `in`, not a truthiness test: `price` is legitimately null for a
          // target that cannot be priced at the decision, and a missing key
          // and an explicit null are the two states being told apart.
          expect(Object.keys(leg)).toEqual(expect.arrayContaining(
            ['price', 'fraction', 'stop', 'trail', 'r_multiple']));
          expect(typeof leg.fraction).toBe('number');
        }
      }
    }
  });
});

describe.each(NAMED)('%s', (_label, strat) => {
  /*
   * THE WORDS AND THE OBJECT MUST AGREE.
   *
   * `shape` is what a person reads on the strategy — "1 SL / 1 TP + runner
   * (50%)" — and the legs are what actually gets ordered. A shape that says
   * "+ runner" over a plan with no runner is the failure this whole file
   * exists to catch, and only the words make it visible.
   */
  test('the declared shape matches the legs it actually carries', () => {
    const plan = strat.sides.long;
    const tp = Number((/(\d+) TP/.exec(strat.shape) || [])[1]);
    expect(plan.legs).toHaveLength(tp);
    const saysRunner = /\+ runner/.test(strat.shape);
    expect(plan.runner > 0).toBe(saysRunner);
    if (saysRunner) {
      const pct = Number((/runner \((\d+)%\)/.exec(strat.shape) || [])[1]);
      expect(Math.round(plan.runner * 100)).toBe(pct);
    }
  });

  /* Legs plus runner is the whole position — not "about" the whole position.
     A protocol summing to 0.9 means a tenth is never ordered, and 90% of a
     correct size looks exactly like a correct size. */
  test('the fractions account for every share', () => {
    const plan = strat.sides.long;
    const total = plan.legs.reduce((n, l) => n + l.fraction, 0) + plan.runner;
    expect(total).toBeCloseTo(1, 6);
  });

  test.each(['long', 'short'])('%s: it becomes the orders it asks for', (side) => {
    const plan = strat.sides[side];
    const { bodies, blocked } = wire(plan, { side });
    expect(blocked).toBeUndefined();

    // A leg whose target has no price at the decision (anchored to an
    // indicator, or left on a rule) cannot rest at a broker — its shares join
    // the runner rather than being sent with an invented target.
    const priced = plan.legs.filter(l => l.price != null);
    const rides = plan.runner > 0
      || plan.legs.some(l => l.price == null)
      || !priced.length;
    expect(bodies).toHaveLength(priced.length + (rides ? 1 : 0));

    // EVERY SHARE THAT WAS SIZED IS ORDERED, and no more.
    expect(bodies.reduce((n, b) => n + b.quantity, 0)).toBe(100);

    // Every order carries the stop — the runner included. That is the whole
    // reason a runner can be left on: it is not unprotected, it rides.
    const expectStop = !plan.trail;
    for (const b of bodies) {
      if (expectStop) expect(b.stop_loss_price).toBeCloseTo(plan.legs[0].stop, 2);
      else expect(b.stop_loss_price_percent ?? b.stop_loss_price_distance).toBeDefined();
    }

    // The targets are the strategy's own, in order, and NONE of them is the
    // `target` argument — which is 99.99 precisely so a fallback to it shows.
    const targets = bodies.map(b => b.take_profit_price).filter(v => v != null);
    expect(targets).toEqual(priced.map(l => Math.round(l.price * 100) / 100));
    expect(targets).not.toContain(99.99);

    // The runner is the one with no target, and it is last.
    if (rides) expect(bodies[bodies.length - 1].take_profit_price).toBeUndefined();

    // A long takes profit ABOVE the entry and a short BELOW it. A sign error
    // here is an order that fills instantly for a loss.
    for (const t of targets) {
      if (side === 'long') expect(t).toBeGreaterThan(CONTRACT.entry);
      else expect(t).toBeLessThan(CONTRACT.entry);
    }
  });

  /*
   * ALERTABLE AND ORDERABLE ARE DIFFERENT QUESTIONS, and the strategy carries
   * the answer. A rule-exit strategy is perfectly valid and must never reach a
   * broker: no broker watches for a VWAP cross, and giving it a price target
   * instead places a different strategy under the same name.
   */
  test('a strategy that cannot be ordered says so, with a reason', () => {
    if (strat.order_ok) {
      expect(strat.order_errors).toEqual([]);
    } else {
      expect(strat.order_errors.length).toBeGreaterThan(0);
    }
  });
});

/*
 * ── THE CANARY ────────────────────────────────────────────────────────────
 *
 * A contract test is only worth having if it FAILS when the contract breaks.
 * These take a real plan out of the fixture, drift it exactly as a rename on
 * the qp side would, and assert the orders come out wrong — which is what
 * proves the tests above are load-bearing rather than decorative.
 *
 * Both drifts are silent in production. Neither throws, neither logs, and both
 * place real money on a strategy nobody tested.
 */
describe('the drift these tests exist to catch', () => {
  // "1 SL / 1 TP + runner (50%)" — the commonest shape, and the one that was
  // once silently placed as "all at 2R" for exactly this reason.
  const withRunner = CONTRACT.strategies.find(s => /\+ runner/.test(s.shape));

  test('the shape is placed correctly to begin with', () => {
    const { bodies } = wire(withRunner.sides.long);
    expect(bodies).toHaveLength(2);
    expect(bodies[0].take_profit_price).toBe(52);
    expect(bodies[1].take_profit_price).toBeUndefined();
  });

  test('`runner` as an object DELETES the runner — the whole position is sold at the target', () => {
    const drifted = { ...withRunner.sides.long, runner: { fraction: 0.5 } };
    const { bodies } = wire(drifted);
    expect(bodies).toHaveLength(1);
    expect(bodies[0].quantity).toBe(100);
    // Every share now leaves at 2R. The half that was meant to run is gone.
    expect(bodies[0].take_profit_price).toBe(52);
  });

  test('a renamed leg price removes every target — the whole position rides', () => {
    const drifted = {
      ...withRunner.sides.long,
      legs: withRunner.sides.long.legs.map(({ price, ...rest }) => ({
        ...rest, tp_price: price,
      })),
    };
    const { bodies } = wire(drifted);
    expect(bodies).toHaveLength(1);
    expect(bodies[0].quantity).toBe(100);
    expect(bodies[0].take_profit_price).toBeUndefined();
  });

  /*
   * The one drift that is NOT silent, and should stay that way. Losing shares
   * is caught by the invariant in splitLegs and refuses to send at all — a
   * position that is not the one the risk settings chose is worse than no
   * position, because it looks exactly like one that is.
   */
  test('fractions that no longer sum to one are refused, not sent short', () => {
    const drifted = {
      ...withRunner.sides.long, runner: 0,
      legs: [{ ...withRunner.sides.long.legs[0], fraction: 0.5 }],
    };
    // The runner is gone, so the leftover joins the last target rather than
    // vanishing — the shares are still all placed, which is the invariant.
    const { bodies } = wire(drifted);
    expect(bodies.reduce((n, b) => n + b.quantity, 0)).toBe(100);
  });
});

/*
 * ── THE FIXTURE MUST STAY CURRENT ─────────────────────────────────────────
 *
 * These tests are worth exactly as much as the fixture's freshness. A change
 * on the qp side that the fixture never learned about would leave every
 * assertion above passing against last month's contract while the live desk
 * sends something else entirely.
 *
 * The check that it is current has to run where qp does, because regenerating
 * it needs Python and the strategy store. It is chart/tests/logic_audit48.py,
 * which fails the qp gate with the command to run. This asserts that guard
 * exists, so deleting it is a failing test rather than a quiet loss of cover.
 */
describe('the fixture cannot silently go stale', () => {
  test('qp checks it is current, and says how to refresh it', () => {
    const audit = fs.readFileSync(path.join(
      __dirname, '..', 'quant-platform', 'chart', 'tests', 'logic_audit48.py'), 'utf8');
    expect(audit).toMatch(/exit_contract\.py --write/);
    const runner = fs.readFileSync(path.join(
      __dirname, '..', 'quant-platform', 'chart', 'tests', 'run_all.py'), 'utf8');
    expect(runner).toMatch(/logic_audit48\.py/);
  });
});
