"""The exit each strategy asks for, frozen as JSON the desk can be tested against.

WHY THIS EXISTS.

The order the broker receives is built in two languages. qp decides the exit —
how many parts the position is cut into, where each part's target is, what the
stop does — and hands it over as `exit_plan`. The desk's `planOrder` reads that
object and turns it into the bodies that go on the wire.

NOTHING CHECKED THAT THE TWO WERE STILL TALKING ABOUT THE SAME OBJECT. The
field names are matched by hand across a language boundary, and every way they
can drift apart is SILENT — the JSON stays valid, SignalStack accepts it, the
broker acts on it, and the position is simply not the one that was tested.

Measured, not imagined. For "half at 2R, half rides the stop", 100 shares:

    correct                        50 @ 2R  +  50 riding the stop
    `runner` becomes a dict        100 @ 2R          — the runner is deleted
    leg `price` renamed            100, no target    — the whole thing rides

One field, either direction, and the strategy that trades is not the strategy
that was backtested. Neither raises. Neither logs. Both spend real money.

So the contract is written down. This exports, for every strategy the platform
holds, the exact `exit_plan` object the live runner would hand to the desk —
priced at a fixed entry and stop so the numbers are checkable by hand — and the
desk's own test suite asserts that each one still becomes the orders that
strategy asks for. A rename on either side then fails a test instead of
quietly changing what gets traded.

    python chart/exports/exit_contract.py            # print it
    python chart/exports/exit_contract.py --write    # update the fixture

The fixture lives with the tests that consume it, in tests/fixtures/, because
it is a test input rather than data the platform reads.

FIXED NUMBERS ON PURPOSE. Entry 50.00, stop 49.00 — so 1R is exactly 1.00 and
every target is readable as a price without arithmetic: 2R is 52.00. A fixture
generated from live prices would change every morning and its diff would say
nothing about whether the contract changed.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from chart import decide as dec          # noqa: E402
from chart import exit_protocol as xp    # noqa: E402
from chart import store                  # noqa: E402

# 1R = 1.00. See the note above.
ENTRY = 50.0
STOP = 49.0
TARGET_R = 2.0

OUT = (pathlib.Path(__file__).resolve().parents[3]
       / 'tests' / 'fixtures' / 'exit-plans.json')


def contract() -> dict:
    """Every strategy's exit plan, as the runner would send it."""
    rows = []
    for s in sorted(store.list_strategies() or [], key=lambda x: str(x.get('id'))):
        proto = xp.normalise(s)
        # LONG and SHORT are not the same object: the targets are on the other
        # side of the entry and the stop rounds the other way, so a contract
        # that only froze one side would not notice a sign error on the other.
        sides = {}
        for side in ('long', 'short'):
            # A short is priced from the mirror stop, so 1R stays 1.00 and the
            # two sides are readable against each other.
            stop = STOP if side == 'long' else (ENTRY + (ENTRY - STOP))
            sides[side] = dec.exit_plan(s, side, ENTRY, stop, TARGET_R)
        rows.append({
            'id': str(s.get('id')),
            'name': s.get('name'),
            'tools': s.get('tools') or [],
            # WHAT THE STRATEGY SAYS ITS EXIT IS, in words, beside the object.
            # The test asserts the object still matches the words: a shape that
            # reads "1 TP + runner" and produces one order is the failure this
            # whole file exists to catch, and only the words make it visible.
            'shape': proto.get('shape'),
            'derived': bool(proto.get('derived')),
            # Alertable and orderable are different questions. A rule-exit
            # strategy is perfectly valid and must never reach a broker, so the
            # contract carries the refusal as part of the strategy's identity.
            'order_ok': proto.get('order_ok', True),
            'order_errors': proto.get('order_errors') or [],
            'sides': sides,
        })
    return {
        'note': ('Generated by chart/exports/exit_contract.py — do not edit by '
                 'hand. Entry 50.00 / stop 49.00, so 1R = 1.00 and 2R = 52.00.'),
        'entry': ENTRY, 'stop': STOP, 'target_r': TARGET_R,
        'strategies': rows,
    }


def dumps(obj) -> str:
    # Stable and diffable: sorted keys, one indent, trailing newline. A fixture
    # whose diff is a reordering is a fixture nobody reads.
    return json.dumps(obj, indent=2, sort_keys=True) + '\n'


if __name__ == '__main__':
    text = dumps(contract())
    if '--write' in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text, encoding='utf-8')
        print(f'wrote {OUT} ({len(contract()["strategies"])} strategies)')
    else:
        print(text, end='')
