const EE_TICKER_TO_THEMES = {
  NVDA: ['AI'],
  PLTR: ['AI'],
  RKLB: ['Space'],
  MSFT: ['AI', 'Cloud'],
  GOOG: ['AI', 'Cloud'],
  GOOGL: ['AI', 'Cloud'],
  AMZN: ['AI', 'Cloud', 'E-Commerce'],
  META: ['AI', 'Social Media'],
  TSLA: ['EV', 'AI'],
  RIVN: ['EV'],
  LCID: ['EV'],
  NIO: ['EV'],
  AAPL: ['Consumer Tech'],
  AMD: ['AI', 'Semiconductors'],
  INTC: ['Semiconductors'],
  QCOM: ['Semiconductors'],
  AVGO: ['Semiconductors', 'AI'],
  ARM: ['Semiconductors', 'AI'],
  SMCI: ['AI', 'Data Center'],
  IONQ: ['Quantum'],
  QUBT: ['Quantum'],
  RGTI: ['Quantum'],
  OKLO: ['Nuclear'],
  SMR: ['Nuclear'],
  CCJ: ['Nuclear'],
  UEC: ['Uranium', 'Nuclear'],
  UUUU: ['Uranium', 'Nuclear'],
  SPCE: ['Space'],
  ASTS: ['Space'],
  LUNR: ['Space'],
  CRWD: ['Cybersecurity'],
  PANW: ['Cybersecurity'],
  ZS: ['Cybersecurity'],
  SHOP: ['E-Commerce'],
  SQ: ['Fintech'],
  PYPL: ['Fintech'],
  COIN: ['Crypto'],
  MSTR: ['Crypto'],
  MARA: ['Crypto'],
  CLSK: ['Crypto'],
  RIOT: ['Crypto'],
  GEO: ['Defense'],
  LMT: ['Defense'],
  RTX: ['Defense'],
  NOC: ['Defense'],
  BA: ['Defense', 'Aerospace'],
  MRNA: ['Biotech'],
  BNTX: ['Biotech'],
  SRPT: ['Biotech'],
  GLP1: ['GLP-1'],
  LLY: ['GLP-1', 'Pharma'],
  NVO: ['GLP-1', 'Pharma'],
};

const EE_INDUSTRY_TO_THEME = {
  Semiconductors: ['AI', 'Semiconductors'],
  'Semiconductor Equipment': ['Semiconductors'],
  'Electronic Components': ['Tech'],
  Software: ['Tech'],
  'Cloud Software': ['AI', 'Cloud'],
  'Internet Software & Services': ['Tech'],
  Biotechnology: ['Biotech'],
  Pharmaceuticals: ['Pharma'],
  'Drug Manufacturers': ['Pharma'],
  'Drug Manufacturers—General': ['Pharma'],
  'Drug Manufacturers—Specialty & Generic': ['Pharma'],
  Uranium: ['Uranium', 'Nuclear'],
  'Nuclear Power': ['Nuclear'],
  'Renewable Energy': ['Clean Energy'],
  'Solar Energy': ['Clean Energy', 'Solar'],
  'Electric Vehicles': ['EV'],
  'Auto Manufacturers': ['EV'],
  'Banks—Regional': ['Fintech', 'Financial'],
  'Capital Markets': ['Fintech'],
  'Insurance—Life': ['Financial'],
  Restaurants: ['Restaurants'],
  'Retail—Specialty': ['Retail'],
  'Internet Retail': ['E-Commerce'],
  Aerospace: ['Aerospace', 'Defense'],
  'Aerospace & Defense': ['Aerospace', 'Defense'],
  'Electronic Gaming & Multimedia': ['Gaming'],
  Gambling: ['Gaming'],
  Cannabis: ['Cannabis'],
  'Medical Devices': ['Medical'],
  'Medical Instruments': ['Medical'],
  'Oil & Gas': ['Energy'],
  'Oil & Gas E&P': ['Energy'],
  'Gold Mining': ['Gold'],
  'Silver Mining': ['Gold', 'Metals'],
  Shipping: ['Shipping'],
  Transportation: ['Transportation'],
};

function classifyByIndustry(industry) {
  return EE_INDUSTRY_TO_THEME[industry] || [];
}

function themesForTicker(ticker, industry) {
  const tickerThemes = EE_TICKER_TO_THEMES[ticker];
  if (tickerThemes && tickerThemes.length > 0) return tickerThemes;
  return classifyByIndustry(industry);
}

module.exports = { themesForTicker, EE_TICKER_TO_THEMES, EE_INDUSTRY_TO_THEME };
